name: CI
on: [push, pull_request]

jobs:
    build:
        name: ci
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with: { node-version: latest }
            - name: Install dependencies
              run: npm clean-install
              env: { HUSKY: 0 }
            - name: Audit dependencies
              run: npm audit && npm audit signatures
            - name: Audit code coverage
              run: npm run test:coverage
            - name: Audit code formatting
              run: npm run format
            - name: Audit code linting
              run: npm run lint
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with: { token: "${{ secrets.CODECOV_TOKEN }}" }
            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with: { token: "${{ secrets.CODECOV_TOKEN }}" }
